# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Admin API Multi Tenant E2E Tests + ODS 7 + Pgsql

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  JIRA_ACCESS_TOKEN: ${{ secrets.JIRA_ACCESS_TOKEN }}
  ADMIN_API_VERSION: "2.2.0"
  PROJECT_ID: "13401"
  CYCLE_NAME: "Automation Cycle"
  TASK_NAME: "API Automation Task"
  FOLDER_NAME: "API Automation Run"
  RESULTS_FILE: "test-xml-results"

permissions: read-all

jobs:
  run-e2e-multitenant-tests:
    defaults:
      run:
        working-directory: ./Application/EdFi.Ods.AdminApi/

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Copy application folder to docker context
        run: |
          mkdir ../../Docker/Application
          cp -r ../EdFi.Ods.AdminApi ../../Docker/Application

      - name: Copy admin api common folder to docker context
        run: cp -r ../EdFi.Ods.AdminApi.Common ../../Docker/Application

      - name: Copy adminApi V1 folder to docker context
        run: cp -r ../EdFi.Ods.AdminApi.V1 ../../Docker/Application

      - name: Copy nuget config to docker context
        run: cp ../NuGet.Config ../../Docker/Application

      - name: Update certificates
        run: cp -r ../../eng/test-certs/ssl ../../Docker/Settings

      - name: Run Admin API
        run: |
          docker compose \
            -f '../../Docker/V2/Compose/pgsql/MultiTenant/compose-build-dev-multi-tenant.yml' \
            --env-file './E2E Tests/V2/gh-action-setup/.automation_pgsql.env' \
            up -d

      - name: Verify containers are running
        run: |
          chmod +x './E2E Tests/V2/gh-action-setup/admin_inspect.sh'
          './E2E Tests/V2/gh-action-setup/admin_inspect.sh' adminapi

      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20"

      - name: Get Token and Set Variables
        run: |
          bash './E2E Tests/V2/Bruno Admin API E2E 2.0 refactor/get_token.sh' multitenant pgsql

      - name: Run Tests
        run: |
          cd './E2E Tests/V2/Bruno Admin API E2E 2.0 refactor/'
          npx @usebruno/cli@latest run --env local --sandbox=developer \
          --insecure -r 'v2/' \
          --reporter-html ./results.html --reporter-junit ./report.xml

      - name: Get Docker logs
        if: failure()
        run: |
          mkdir docker-logs
          docker logs ed-fi-db-admin-adminapi-tenant1 > docker-logs/ed-fi-db-admin-adminapi-tenant1.log
          docker logs ed-fi-db-admin-adminapi-tenant2 > docker-logs/ed-fi-db-admin-adminapi-tenant2.log
          docker logs adminapi > docker-logs/adminapi.log

      - name: Upload Docker logs
        if: failure()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: docker-logs
          path: Application/EdFi.Ods.AdminApi/docker-logs/
          retention-days: 5

      - name: Upload Html results
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: success() || failure()
        with:
          name: test-html-results
          path: Application/EdFi.Ods.AdminApi/E2E Tests/V2/Bruno Admin API E2E 2.0 refactor/results.html
          retention-days: 5

      - name: Upload xml results
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: success() || failure()
        with:
          name: test-xml-results
          path: Application/EdFi.Ods.AdminApi/E2E Tests/V2/Bruno Admin API E2E 2.0 refactor/report.xml
          retention-days: 5

  report:
    defaults:
      run:
        shell: pwsh
    needs:
      - run-e2e-multitenant-tests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
