# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Admin API E2E Tests + ODS 6 + MSSQL

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "*-hotfix"

env:
  JIRA_ACCESS_TOKEN: ${{ secrets.JIRA_ACCESS_TOKEN }}
  ADMIN_API_VERSION: "1.2"
  PROJECT_ID: "13401"
  CYCLE_NAME: "Automation Cycle"
  TASK_NAME: "API Automation Task"
  FOLDER_NAME: "API Automation Run"
  RESULTS_FILE: "test-results"

permissions: read-all

jobs:
  run-e2e-tests:
    defaults:
      run:
        working-directory: ./Application/EdFi.Ods.AdminApi/

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Copy application folder to docker context
        run: |
          mkdir ../../Docker/Application
          cp -r ../EdFi.Ods.AdminApi ../../Docker/Application

      - name: Copy nuget config to docker context
        run: cp ../NuGet.Config ../../Docker/Application

      - name: Update certificates
        run: cp -r ../../eng/test-certs/ssl ../../Docker/Settings

      - name: Run Admin API
        run: |
          docker compose \
            -f '../../Docker/V1/Compose/mssql/compose-build-dev.yml' \
            --env-file './E2E Tests/V1/gh-action-setup/.automation.env' \
            up -d

      - name: Verify containers are running
        run: |
          chmod +x './E2E Tests/V1/gh-action-setup/inspect.sh'
          './E2E Tests/V1/gh-action-setup/inspect.sh'

      - name: Setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: "20"

      - name: Get Token and Set Variables
        run: |
          bash './E2E Tests/V1/Bruno Admin API E2E refactor/get_token.sh'

      - name: Run Tests
        run: |
          cd './E2E Tests/V1/Bruno Admin API E2E refactor/'
          npx @usebruno/cli@latest run --env local --sandbox=developer \
          --insecure 'v1/Vendors' 'v1/OdsInstances' 'v1/ClaimSets' 'v1/Application' \
          --reporter-html ./results.html --reporter-junit ./report.xml

      - name: Get Docker logs
        if: failure()
        run: |
          mkdir docker-logs
          docker logs adminapi > docker-logs/adminapi.log
          docker logs ed-fi-db-admin-adminapi > docker-logs/ed-fi-db-admin.log
          docker logs ed-fi-gateway-adminapi > docker-logs/ed-fi-gateway.log

      - name: Upload Docker logs
        if: failure()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: docker-logs
          path: Application/EdFi.Ods.AdminApi/docker-logs/
          retention-days: 10

      - name: Upload Html results
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: success() || failure()
        with:
          name: test-html-results
          path: Application/EdFi.Ods.AdminApi/E2E Tests/V1/Bruno Admin API E2E refactor/results.html
          retention-days: 10

      - name: Upload xml results
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        if: success() || failure()
        with:
          name: test-results
          path: Application/EdFi.Ods.AdminApi/E2E Tests/V1/Bruno Admin API E2E refactor/report.xml
          retention-days: 10

  report:
    defaults:
      run:
        shell: pwsh
    needs:
      - run-e2e-tests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Download artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
